name: Test CI

on: [push, pull_request]

jobs:
  test:
    name: Build and test
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        java-version: ['1.8', '11', '15']

    steps:
      - name: Debug test
        run: echo $GITHUB_REF

  publish:
    name: Publish to OSSRH
    runs-on: 'ubuntu-latest'

    needs: test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Debug publish
        run: echo $GITHUB_REF
